[package]
name = "egor00f/switch"

description = "small lua switch implementation"

version = "0.1.1"

registry = "https://github.com/UpliftGames/wally-index"

# or server
realm = "shared"

license = "MIT"

repository = "https://github/ukuroks-games/switch"

authors = ["Egor00f <velikiydolbayeb@gamil.com>"]

exclude = ["*"]

include = [
	"src",
	"src/**",
	"wally.toml",
	"README.md",
	"init.lua"
]

private = false

[dependencies]


[server-dependencies]


[dev-dependencies]

